### ISSUE TITLE
Mac/Linux support?

### ISSUE THREAD

**Issue by canalnoises** [brion/hdrfix#5]
Apologies in advance for my ignorance, but is it possible to compile hdrfix for macOS and/or Linux? This tool sounds like exactly what I'm looking for to help a friend convert JXR screenshots from his Xbox.

**Comment by brion** [comment]
Yes, I try to keep it running on all three OSs. :) Currently I don't make binaries except for Windows though, so you have to build it manually.

Build requirements:
* Rust compiler (use the rustup installer from https://www.rust-lang.org/learn/get-started )
* C/C++ compiler for some of the libraries (Xcode & command line tools on Mac, or the usual build tools on Linux)

Check out the source and run:
```bash
cargo install path=.
```

and it'll be available as 'hdrfix'.

Let me know if you have any trouble.
